# Credit Card Fraud Detection:

We use real data set with real credit card transactions that had been anonymize for us.

In [1]:
# To handle datasets
import pandas as pd
import numpy as np

# for plotting
import matplotlib.pyplot as plt
% matplotlib inline


In [2]:
# to display all the columns of the dataframe in the notebook
pd.pandas.set_option('display.max_columns', None)

In [3]:
# Import data 
df = pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [4]:
# rows and columns of the data
print(df.shape)


(284807, 31)


In [5]:
# Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df['normalizedAmount'] = sc.fit_transform(df['Amount'].values.reshape(-1,1))
df = df.drop(['Amount'],axis=1)

In [6]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Class  normalizedAmount  
0      0          0.244964  
1      0         -0.342475  
2      0          1.160686  
3      0          0.140534  
4      0         -0.073403

In [7]:
df = df.drop(['Time'],axis=1)
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Class  normalizedAmount  
0      0          0.244964  
1      0         -0.342475  
2      0          1.160686  
3      0          0.140534  
4      0         -0.073403

In [8]:
# split into features ans Labels
X = df.drop(['Class'],axis=1)
y = df['Class']

#Same as above
# X = data.iloc[:, data.columns != 'Class']
# y = data.iloc[:, data.columns == 'Class']

In [9]:
X.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   normalizedAmount  
0          0.244964  
1         -0.342475  
2          1.160686  
3          0.140534  
4         -0.073403

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=0)

In [11]:
X_train.shape

(199364, 29)

In [12]:
X_test.shape

(85443, 29)

## Deep neural network:

In [13]:
# Importing the Keras libraries and packages 
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

C:\Users\Manish Garg\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [14]:
model = Sequential([
    Dense(units=16, input_dim = 29,activation='relu'),
    Dense(units=24,activation='relu'),
    Dropout(0.5),
    Dense(20,activation='relu'),
    Dense(24,activation='relu'),
    Dense(1,activation='sigmoid'),
])

In [15]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                480       
_________________________________________________________________
dense_2 (Dense)              (None, 24)                408       
_________________________________________________________________
dropout_1 (Dropout)          (None, 24)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 20)                500       
_________________________________________________________________
dense_4 (Dense)              (None, 24)                504       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 25        
Total params: 1,917
Trainable params: 1,917
Non-trainable params: 0
_________________________________________________________________


In [16]:
# Compiling the Neural Network
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [17]:
# Fitting the Neural Network to the Training set
model.fit(X_train,y_train,batch_size=15,epochs=6)

Epoch 1/6
199364/199364 [==============================] - 27s 138us/step - loss: 0.0133 - acc: 0.9970
Epoch 2/6
199364/199364 [==============================] - 27s 133us/step - loss: 0.0043 - acc: 0.9994
Epoch 3/6
199364/199364 [==============================] - 27s 135us/step - loss: 0.0040 - acc: 0.9993
Epoch 4/6
199364/199364 [==============================] - 26s 132us/step - loss: 0.0036 - acc: 0.9994
Epoch 5/6
199364/199364 [==============================] - 25s 126us/step - loss: 0.0036 - acc: 0.9994
Epoch 6/6
199364/199364 [==============================] - 25s 127us/step - loss: 0.0035 - acc: 0.9994


In [18]:
score = model.evaluate(X_test, y_test)

85443/85443 [==============================] - 2s 25us/step


In [19]:
print(score)

[0.0048954390004381535, 0.9994148145547324]


In [20]:
y_pred = model.predict(X_test)


In [21]:
y_pred

array([[4.6644194e-10],
       [6.8512951e-09],
       [2.9412570e-10],
       ...,
       [3.7159527e-08],
       [1.9025249e-07],
       [2.7503506e-11]], dtype=float32)

In [22]:
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(y_test, y_pred.round())
cnf_matrix

array([[85276,    20],
       [   30,   117]], dtype=int64)

## Sampling:
Oversampling and undersampling in data analysis are techniques used to adjust the class distribution of a data set (i.e. the ratio between the different classes/categories represented). These terms are used both in statistical sampling, survey design methodology and in machine learning.
### UnderSampling:

In [23]:
# choose the index of sample which  have class 1(Fraud)
fraud_indices = np.array(df[df.Class == 1].index)


In [24]:
type(df[df.Class == 1].index)

pandas.core.indexes.numeric.Int64Index

In [25]:
number_records_fraud = len(fraud_indices)
print(number_records_fraud)

492


In [26]:
# choose the index of sample which  have class 0(normal)
normal_indices = df[df.Class == 0].index
normal_indices

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            284797, 284798, 284799, 284800, 284801, 284802, 284803, 284804,
            284805, 284806],
           dtype='int64', length=284315)

In [27]:
# choose random samples(no.=492)
random_normal_indices= np.random.choice(normal_indices, number_records_fraud, replace=False)

In [28]:
random_normal_indices

array([136149, 255085, 161435, 226309, 163604, 247082,  10071, 189820,
        95631, 259063, 214805, 165910,  57489, 257970, 281052,  61642,
       142962,  61147,  20246,  87017, 130195, 126125, 221695,  65555,
       175302, 260743, 230221,  97592,  81625, 203577, 118406, 274883,
        74022, 239052, 151051, 195916, 164869,   7543, 261758,  74465,
        12983,  87246, 118577, 176217, 263519, 119465, 119713,  29322,
       217099,  62838,  44674, 163428,  89264, 169547, 173757, 256227,
        94413, 174211, 218697, 100679,  80336, 174930,  40496, 279646,
       218727, 112134, 152934,  90350, 224164, 176880,  93476,  82409,
       170045, 234987,  11175, 279751, 269451,  12235, 147516, 205298,
       133224,  94785, 273936, 167358,  81848, 155596, 188243, 252642,
       151586,  53492, 238086, 157050,  55235, 250382, 211613, 240511,
       277838,  12171, 165645, 119750, 219197,  64958,  63968, 240073,
       250691, 245384,   1187, 197311, 102690, 196972, 250269,  69820,
      

In [29]:
print(len(random_normal_indices))

492


In [30]:
under_sample_indices = np.concatenate([fraud_indices,random_normal_indices])
print(len(under_sample_indices))

984


In [31]:
under_sample_data = df.iloc[under_sample_indices,:]
under_sample_data.head()

V1        V2        V3        V4        V5        V6        V7  \
541  -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545 -2.537387   
623  -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823  0.325574   
4920 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788  0.562320   
6108 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536 -3.496197   
6329  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746  1.713445   

            V8        V9       V10       V11        V12       V13       V14  \
541   1.391657 -2.770089 -2.772272  3.202033  -2.899907 -0.595222 -4.289254   
623  -0.067794 -0.270953 -0.838587 -0.414575  -0.503141  0.676502 -1.692029   
4920 -0.399147 -0.238253 -1.525412  2.032912  -6.560124  0.022937 -1.470102   
6108 -0.248778 -0.247768 -4.801637  4.895844 -10.912819  0.184372 -6.771097   
6329 -0.496358 -1.282858 -2.447469  2.101344  -4.609628  1.464378 -6.079337   

           V15       V16        V17       V18       V19       V20       V21  \
541   0.389724 -1.140747  -2.830056 -0.016822  0.416956  0.126911  0.517232   
623   2.000635  0.666780   0.599717  1.725321  0.283345  2.102339  0.661696   
4920 -0.698826 -2.282194  -4.781831 -2.615665 -1.334441 -0.430022 -0.294166   
6108 -0.007326 -7.358083 -12.598419 -5.131549  0.308334 -0.171608  0.573574   
6329 -0.339237  2.581851   6.739384  3.042493 -2.721853  0.009061 -0.379068   

           V22       V23       V24       V25       V26       V27       V28  \
541  -0.035049 -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276   
623   0.435477  1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764   
4920 -0.932391  0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029   
6108  0.176968 -0.436207 -0.053502  0.252405 -0.657488 -0.827136  0.849573   
6329 -0.704181 -0.656805 -1.632653  1.488901  0.566797 -0.010016  0.146793   

      Class  normalizedAmount  
541       1         -0.353229  
623       1          1.761758  
4920      1          0.606031  
6108      1         -0.117342  
6329      1         -0.349231

In [32]:
# split into features ans Labels
under_X = under_sample_data.drop(['Class'],axis=1)
under_y= under_sample_data['Class']

In [33]:
X_train, X_test, y_train, y_test = train_test_split(under_X,under_y, test_size=0.3)

In [34]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                480       
_________________________________________________________________
dense_2 (Dense)              (None, 24)                408       
_________________________________________________________________
dropout_1 (Dropout)          (None, 24)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 20)                500       
_________________________________________________________________
dense_4 (Dense)              (None, 24)                504       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 25        
Total params: 1,917
Trainable params: 1,917
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=15,epochs=5)

Epoch 1/5
688/688 [==============================] - 1s 1ms/step - loss: 0.6267 - acc: 0.9142
Epoch 2/5
688/688 [==============================] - 0s 143us/step - loss: 0.2313 - acc: 0.9201
Epoch 3/5
688/688 [==============================] - 0s 146us/step - loss: 0.1915 - acc: 0.9288
Epoch 4/5
688/688 [==============================] - 0s 112us/step - loss: 0.1586 - acc: 0.9360
Epoch 5/5
688/688 [==============================] - 0s 129us/step - loss: 0.1622 - acc: 0.9375


In [36]:
y_pred = model.predict(X_test)
cnf_matrix = confusion_matrix(y_test, y_pred.round())
cnf_matrix

array([[156,   0],
       [ 20, 120]], dtype=int64)

## SMOTE:
you can install it by the command `pip install -U imbalanced-learn`

In [37]:
from imblearn.over_sampling import SMOTE

C:\Users\Manish Garg\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [38]:
X_resample, y_resample = SMOTE().fit_sample(X,y)

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X_resample,y_resample,test_size=0.3)

In [40]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=15,epochs=5)

Epoch 1/5
398041/398041 [==============================] - 54s 137us/step - loss: 0.0320 - acc: 0.9885
Epoch 2/5
398041/398041 [==============================] - 54s 136us/step - loss: 0.0135 - acc: 0.9963
Epoch 3/5
398041/398041 [==============================] - 55s 138us/step - loss: 0.0106 - acc: 0.9973
Epoch 4/5
398041/398041 [==============================] - 54s 136us/step - loss: 0.0096 - acc: 0.9977
Epoch 5/5
398041/398041 [==============================] - 53s 133us/step - loss: 0.0083 - acc: 0.9981


In [41]:
y_pred = model.predict(X_test)

cnf_matrix = confusion_matrix(y_test, y_pred.round())
cnf_matrix

array([[84997,   250],
       [   34, 85308]], dtype=int64)

## Great!!😍